# Generated by Django 5.0 on 2026-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='categories_icons', verbose_name='Иконка')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('short_description', models.CharField(max_length=400, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Category',
            },
        ),
    ]
