# Generated by Django 4.2.7 on 2023-11-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='books_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
