# Generated by Django 4.2.7 on 2023-12-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_books_number_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='books_number',
        ),
    ]
