services:
  pgdb:
    image: postgres:17.2
    restart: always
    container_name: 'pgdb'
    environment:
      POSTGRES_DB: 'active_scope'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  backend:
    build: .
    command: >
      sh -c "cd server && 
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/usr/src/app/server
    container_name: 'backend'
    environment:
      DB_NAME: 'new_authors'
      DB_USER: 'postgres'
      DB_PASSWORD: '123456'
      DB_HOST: 'pgdb'
      DB_PORT: '5432'
    ports:
      - '8080:8080'
    depends_on:
      - pgdb

volumes:
  pgdbdata: {}