# Generated by Django 4.2.7 on 2023-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='Полное имя (ФИО)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='Является автором'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='short_description',
            field=models.CharField(max_length=450, verbose_name='Краткое описание'),
        ),
    ]
