# Generated by Django 4.2.7 on 2023-12-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_profile_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='creation_date',
            new_name='publication_date',
        ),
    ]
